# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-25 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nestauth',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
