# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-25 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160825_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.CharField(max_length=255)),
                ('nest_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.NestAuth')),
            ],
        ),
    ]
