# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-27 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='vacation_mode',
            field=models.BooleanField(default=False),
        ),
    ]
